logger with streams
Oleh-Mashovets/nodejs24_hw_oleh_mashovets pull request #4
Opened 2024-02-11 19:07 UTC by Oleh-Mashovets

2024-02-11 19:44 UTC, evhenious commented on utils/logger.js
> +      } else if (LOG_LEVEL === "warn") {
Для чого нам пусті умови? )

2024-02-11 19:48 UTC, evhenious commented on utils/logger.js
> +    const logEntry = `[${new Date().toISOString()}] ${moduleName} ${level.toUpperCase()}: ${message}\n`;
Щось тут у тебе з месаджем в файлі не те відбувається) бачив логи свої?
<img width="791" alt="image" src="https://github.com/Oleh-Mashovets/nodejs24_hw_oleh_mashovets/assets/5249435/58899ef4-38b1-47bd-81c0-d63de2b602bb">

оці бінарні вставки - це позначення кольорів. Але текстовий лог не знає що це таке. Тут потрібно позбутись кольорів для файлстріма, але залишити для консолі

2024-02-11 19:55 UTC, evhenious requested changes
Майже все ОК ) розберись будь ласка з непротрібною бінарщіною в лог файлах)

2024-02-12 15:46 UTC, Oleh-Mashovets commented on utils/logger.js
> +      } else if (LOG_LEVEL === "warn") {
Виправив, то мабуть замріявся:)

2024-02-12 15:52 UTC, evhenious commented on utils/logger.js
> +    return message.replace(/\x1B\[\d+m/g,'');
Воу-воу! ні, ну можна звісно й так, але булоб може крще розділити месаджі на два: один з кольорами йде в консоль, інший з чимось типу `JSON.stringify(args)` (щоб не було [object Object] в файлі) йде в файлстрім... ну але залишу на твою відповідальність ;)

2024-02-12 15:55 UTC, Oleh-Mashovets commented on utils/logger.js
> +    return message.replace(/\x1B\[\d+m/g,'');
аxаx, добре, троxи пізніше ще подивлюсь)

2024-02-12 16:22 UTC, Oleh-Mashovets commented on utils/logger.js
> +    return message.replace(/\x1B\[\d+m/g,'');
Зміни внесено

2024-02-12 17:44 UTC, evhenious approved these changes

2024-02-12 17:44 UTC, merged